name: Velvet VPN – Создать подписку

on:
  workflow_dispatch:  # Запуск вручную из интерфейса GitHub

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование кода
        uses: actions/checkout@v4

      - name: Установка .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Установка Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'

      - name: Установка ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Восстановление зависимостей
        run: dotnet restore

      - name: Сборка проекта
        run: dotnet build --configuration Release --no-restore

      - name: Запуск программы
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: dotnet run --configuration Release --no-build
